version: "3"
services: 
  hub:
    image: selenium/hub:3.141.59-gold
    ports: 
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-gold
    depends_on: 
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59-gold
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  amazon-chrome:
    image: lucikaaa03/amazontest1
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=testngParallel.xml
    volumes:
      - ./chrome-results/amazontest-chrome:/usr/share/project/test-output
  amazon-firefox:
    image: lucikaaa03/amazontest1
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=firefox
      - MODULE=testngParallel.xml
    volumes:
      - ./firefox-results/amazontest-firefox:/usr/share/project/test-output
