version: "3"
services: 
  hub:
    image: selenium/hub:3.141.59-gold
    ports: 
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-gold
    depends_on: 
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59-gold
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  amazon-test:
    image: lucikaaa03/amazontest
    depends_on: 
      - chrome 
      - firefox 
    environment: 
      - HUB_HOST=hub 
      - BROWSER=chrome 
      - MODULE=testngParallel.xml
